# Generated by Django 3.2.5 on 2022-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2022-07-12'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
